RPSSL/Models/ApiResponse.cs
using System.Net;

namespace RPSSL.Models
{
    public abstract class ApiResponseBase
    {
        public bool IsSuccessful { get; protected set; }
    }

    public class BadApiResponse : ApiResponseBase
    {
        public BadApiResponse() 
        {
            Error = new Error((int)HttpStatusCode.InternalServerError, "Something went wrong");
        }

        public BadApiResponse(string message)
        {
            Error = new Error(default, message);
        }

        public BadApiResponse(int code, string message)
        {
            Error = new Error(code, message);
        }

        public Error? Error { get; private set; }
    }

    public class ApiResponse<T> : ApiResponseBase
    {
        private ApiResponse() {}

        public ApiResponse(T? data)
        {
            IsSuccessful = true;
            Data = data;
        }

        public T? Data { get; set; }        
    }
}

RPSSL/Models/Error.cs
namespace RPSSL.Models
{
    public record class Error (int Code, string Message);
}

RPSSL/Models/GameServicePlayRequestModel.cs
using RPSSL.Common.Enums;

namespace RPSSL.Models
{
    public record GameServicePlayRequestModel (ChoiceType Player, string? PlayerName);
}

RPSSL/Controllers/BaseApiController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace RPSSL.Controllers
{
    public class BaseApiController : Controller
    {
        protected ILogger logger;
        public BaseApiController(ILogger logger)
        {

            this.logger = logger;
        }
    }
}

RPSSL/Controllers/GameServiceController.cs
using Microsoft.AspNetCore.Mvc;
using RPSSL.Common.Entities;
using RPSSL.Models;
using RPSSL.BL.Services;
using RPSSL.BL.Exceptions;
using RPSSL.BL.Services.Models;

namespace RPSSL.Controllers
{
    //[Route("api/[controller]")] to comply the requirements
    [Route("")]
    [ApiController]
    public class GameServiceController : BaseApiController
    {
        private GameService gameService;

        public GameServiceController (GameService gameService, ILogger<GameServiceController> logger) : base(logger)
        {
            this.gameService = gameService;
        }

        [HttpGet("choice")]
        public async Task<ApiResponseBase> GetChoice()
        {
            try
            {
                return new ApiResponse<Choice>(await gameService.GetRandomChoiceAsync());
            }
            catch(OurUserFriendlyException ufe)
            {
                logger.LogWarning(ufe, "GetChoice");

                return new BadApiResponse(ufe.Message);
            }
            catch(Exception e)
            {
                logger.LogError(e, "GetChoice");

                return new BadApiResponse();
            }
        }

        [HttpGet("choices")]
        public ApiResponseBase GetChoices()
        {
            try
            {
                return new ApiResponse<IEnumerable<Choice>>(gameService.GetChoices());
            }
            catch (OurUserFriendlyException ufe)
            {
                logger.LogWarning(ufe, "GetChoices");

                return new BadApiResponse(ufe.Message);
            }
            catch (Exception e)
            {
                logger.LogError(e, "GetChoices");

                return new BadApiResponse();
            }
        }

        [HttpPost("play")]
        public async Task<ApiResponseBase> Play(GameServicePlayRequestModel model)
        {
            try
            {
                return new ApiResponse<GameServiceRoundProcessingResponse>(await gameService.ProcessRound(model.Player, model.PlayerName));
            }
            catch (OurUserFriendlyException ufe)
            {
                logger.LogWarning(ufe, "Play");

                return new BadApiResponse(ufe.Message);
            }
            catch (Exception e)
            {
                logger.LogError(e, "Play");

                return new BadApiResponse();
            }
        }
    }
}

RPSSL/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RPSSL.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

RPSSL/Pages/Leaderboard.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RPSSL.BL.Services;
using RPSSL.BL.Services.Models;

namespace RPSSL.Pages
{
    public class LeaderboardModel : PageModel
    {
        private readonly ILogger<LeaderboardModel> logger;
        private readonly GameService gameService;
        public List<GameServiceLeaderboardRecordResponse> Records { get; private set; }

        public LeaderboardModel(ILogger<LeaderboardModel> logger, GameService gameService)
        {
            this.logger = logger;
            this.gameService = gameService;

            Records = gameService.GetLeaderboard().ToList();
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnPostResetAsync()
        {
            gameService.ResetLeaderBoard();

            return RedirectToPage();
        }
    }
}

RPSSL/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Let's play";
}

<div class="text-center">
    <div id="computer">Computer</div>
    <div id="computerChoice"><div></div></div>
    <div id="player">
        <div id="playerName"><span></span> <i class="fa fa-pencil" aria-hidden="true"></i></div>
        <div id="playerEdit" class="form-inline" style="display:none">
            <div class="form-group mx-sm-3 mb-2">
                <label for="playerEditValue">Name</label>
                <input class="form-control text-center" id="playerEditValue" placeholder="Enter your name">
            </div>
            <button type="submit" class="btn btn-outline-primary mb-2" onclick="saveEditedName()">Save</button>
            <button type="submit" class="btn btn-outline-secondary mb-2" onclick="discardEditedNameChaneges()">Cancel</button>
        </div>
    </div>
    <div id="playerChoice"><div></div></div>
    <div id="choicesList"></div>
    <div id="history"></div>
</div>

@section Scripts
{
    <script src="https://use.fontawesome.com/65757cbd1c.js"></script>
}

RPSSL/Pages/Leaderboard.cshtml
@page
@using RPSSL.BL.Services
@model LeaderboardModel

@{
    int n = 1;
}

@if (Model.Records.Any())
{
    <div id="resetButtonWrapper">
        <form method="post">
            <button type="submit" class="btn btn-danger" asp-page-handler="reset">
                Reset
            </button>
        </form>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Score</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var record in Model.Records)
            {
                <tr>
                    <th scope="row">@(n++)</th>
                    <td>@record.Name</td>
                    <td>@record.Score</td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h4 class="text-center mt-5">There is nothing to show yet.</h4>
}

RPSSL/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RPSSL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RPSSL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">RPSSL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Play</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Leaderboard">Leaderboard</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>